name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  exit-codes:
    runs-on: ubuntu-latest
    steps:
      - name: Successful command
        run: |
          echo "This command will succeed"
          exit 0

      - name: Failed command
        run: |
          echo "This command will fail"
          exit 1

      - name: Never executed
        run: echo "This step will not run because previous step failed"